//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInfo
    {
        public int ID { get; set; }
        public string Account_Name { get; set; }
        public Nullable<int> Account_Number { get; set; }
        public Nullable<int> Account_Balance { get; set; }
    }
}
